
const Saponification = [{name:'Abyssian Oil',
              lye:0.12,
              potash: 0.168,
              lauric: 0,
              myristic: 0,
              palmitic: 0,
              stearic:0,
              ricinoleic: 0,
              oleic: 18,
              linoleic: 11,
              linolenic: 4,
              },

              {name:"Almond Oil",
               lye: 0.1367,
               potash: 0.1925,
               lauric: 0,
               myristic: 0,
               palmitic: 7,
               stearic: 0,
               ricinoleic: 0,
               oleic: 71,
               linoleic: 18,
               linolenic: 0,
              },

              {name: "Aloe Vera Butter",
               lye: 0.1788,
               potash: 0.2518,
               lauric: 45,
               myristic: 18,
               palmitic: 8,
               stearic: 3,
               ricinoleic: 0,
               oleic: 7,
               linoleic: 2,
               linolenic: 0,
              },

              { name: "Apricot Kernel Oil",
                lye: 0.1378,
                potash: 0.1941,
                lauric: 0,
                myristic: 0,
                palmitic: 6,
                stearic: 0,
                ricinoleic: 0,
                oleic: 66,
                linoleic: 27,
                linolenic: 0,
              },

              { name:'Argan Oil',
                lye: 0.136,
                potash:0.191,
                lauric: 0,
                myristic: 1,
                palmitic: 14,
                stearic: 0,
                ricinoleic: 0,
                oleic: 46,
                linoleic: 34,
                linolenic: 1,
              },

              { name: "Avocado Butter",
                lye: 0.1339,
                potash: 0.1886,
                lauric: 0,
                myristic: 0,
                palmitic: 21,
                stearic: 10,
                ricinoleic: 0,
                oleic: 53,
                linoleic: 6,
                linolenic: 2,
              },

              { name: "Avocado Oil",
                lye: 0.1337,
                potash: 0.1883,
                lauric: 0,
                myristic: 0,
                palmitic: 20,
                stearic: 2,
                ricinoleic: 0,
                oleic: 58,
                linoleic: 12,
                linolenic: 0,
              },

              { name: "Babassu Nut Oil",
                lye: 0.1749,
                potash: 0.2463,
                lauric: 50,
                myristic: 20,
                palmitic: 11,
                stearic: 4,
                ricinoleic: 0,
                oleic: 10,
                linoleic: 0,
                linolenic: 0,
              },

              { name: "Beeswax",
                lye: 0.0689,
                potash: 0.0970,
                lauric: 0,
                myristic: 0,
                palmitic: 0,
                stearic: 0,
                ricinoleic: 0,
                oleic: 0,
                linoleic: 0,
                linolenic: 0,
              },

              { name: "Borage Oil",
                lye: 0.1339,
                potash: 0.1886,
                lauric: 0,
                myristic: 0,
                palmitic: 10,
                stearic: 4,
                ricinoleic: 0,
                oleic: 20,
                linoleic: 43,
                linolenic: 5,
              },

              { name: 'Brazil Nut Oil',
                lye: 0.135,
                potash: 0.19,
                lauric: 0,
                myristic: 0,
                palmitic: 13,
                stearic: 11,
                ricinoleic: 0,
                oleic: 39,
                linoleic: 36,
                linolenic: 0,
              },

              { name: "Candelilla Wax",
                lye: 0.0322,
                potash: 0.0454,
                lauric: 0,
                myristic: 0,
                palmitic: 0,
                stearic: 0,
                ricinoleic: 0,
                oleic: 0,
                linoleic: 0,
                linolenic: 0,
              },

              { name: "Canola Oil",
                lye: 0.1328,
                potash: 0.1870,
                lauric: 0,
                myristic: 0,
                palmitic: 4,
                stearic: 2,
                ricinoleic: 0,
                oleic: 61,
                linoleic: 21,
                linolenic: 9,
              },

              { name: "Canola Oil, High Oleic Acid",
                lye: 0.1330,
                potash: 0.1873,
                lauric: 0,
                myristic: 0,
                palmitic: 4,
                stearic: 2,
                ricinoleic: 0,
                oleic: 74,
                linoleic: 12,
                linolenic: 4,
              },

              { name: "Castor Bean Oil",
                lye: 0.1286,
                potash: 0.1811,
                lauric: 0,
                myristic: 0,
                palmitic: 0,
                stearic: 0,
                ricinoleic: 90,
                oleic: 4,
                linoleic: 4,
                linolenic: 0,
              },

              { name: "Cherry Kernel Oil",
                lye: 0.1389,
                potash: 0.1956,
                lauric: 0,
                myristic: 0,
                palmitic: 8,
                stearic: 3,
                ricinoleic: 0,
                oleic: 31,
                linoleic: 45,
                linolenic: 11,
              },

              { name: "Chicken Fat",
                lye: 0.1356,
                potash: 0.1910,
                lauric: 0,
                myristic: 1,
                palmitic: 25,
                stearic: 7,
                ricinoleic: 0,
                oleic: 38,
                linoleic: 21,
                linolenic: 0,
              },

              { name: "Cocoa Butter",
                lye: 0.1378,
                potash: 0.1941,
                lauric: 0,
                myristic: 0,
                palmitic: 28,
                stearic: 33,
                ricinoleic: 0,
                oleic: 35,
                linoleic: 3,
                linolenic: 0,
              },

              { name: "Coconut Oil, Refined 76",
                lye: 0.1910,
                potash: 0.2690,
                lauric: 48,
                myristic: 19,
                palmitic: 9,
                stearic: 3,
                ricinoleic: 0,
                oleic: 8,
                linoleic: 2,
                linolenic: 0,
              },

              { name: "Coconut Oil, Hydrogenated 92",
                lye: 0.1910,
                potash: 0.2690,
                lauric: 48,
                myristic: 19,
                palmitic: 9,
                stearic: 3,
                ricinoleic: 0,
                oleic: 8,
                linoleic: 2,
                linolenic: 0,
              },

              { name: "Coconut Oil, Fractionated/Saturated",
                lye: 0.2321,
                potash: 0.3269,
                lauric: 2,
                myristic: 1,
                palmitic: 0,
                stearic: 0,
                ricinoleic: 0,
                oleic: 0,
                linoleic: 0,
                linolenic: 0,
              },

              { name: 'Coffee Bean Oil, green',
                lye: 0.132,
                potash: 0.185,
                lauric: 0,
                myristic: 0,
                palmitic: 38,
                stearic: 8,
                ricinoleic: 0,
                oleic: 9,
                linoleic: 39,
                linolenic: 2,
              },

              { name: 'Coffee Bean Oil, roasted',
                lye: 0.128,
                potash: 0.180,
                lauric: 0,
                myristic: 0,
                palmitic: 40,
                stearic: 0,
                ricinoleic: 0,
                oleic: 8,
                linoleic: 38,
                linolenic: 2,
              },

              { name: "Corn Oil",
                lye: 0.1368,
                potash: 0.1927,
                lauric: 0,
                myristic: 0,
                palmitic: 12,
                stearic: 2,
                ricinoleic: 0,
                oleic: 32,
                linoleic: 51,
                linolenic: 1,
              },

              { name: "Cottonseed Oil",
                lye: 0.1387,
                potash: 0.1954,
                lauric: 0,
                myristic: 0,
                palmitic: 13,
                stearic: 13,
                ricinoleic: 0,
                oleic: 18,
                linoleic: 52,
                linolenic: 1,
              },

              { name: "Crisco Vegetable Shortening",
                lye: 0.1369,
                potash: 0.1928,
                lauric: 0,
                myristic: 0,
                palmitic: 13,
                stearic: 13,
                ricinoleic: 0,
                oleic: 18,
                linoleic: 52,
                linolenic: 0,
              },

              { name: "Emu Oil",
                lye: 0.1377,
                potash: 0.1939,
                lauric: 0,
                myristic: 0,
                palmitic: 23,
                stearic: 9,
                ricinoleic: 0,
                oleic: 47,
                linoleic: 8,
                linolenic: 0,
              },

              { name: "Evening Primrose Oil",
                lye: 0.1362,
                potash: 0.1918,
                lauric: 0,
                myristic: 0,
                palmitic: 0,
                stearic: 0,
                ricinoleic: 0,
                oleic: 0,
                linoleic: 80,
                linolenic: 9,
              },

              { name: "Flaxseed Oil",
                lye: 0.1358,
                potash: 0.1913,
                lauric: 0,
                myristic: 0,
                palmitic: 6,
                stearic: 3,
                ricinoleic: 0,
                oleic: 27,
                linoleic: 13,
                linolenic: 50,
              },

              { name: "Goose Fat",
                lye: 0.1349,
                potash: 0.1900,
                lauric: 0,
                myristic: 0,
                palmitic: 21,
                stearic: 6,
                ricinoleic: 0,
                oleic: 64,
                linoleic: 10,
                linolenic: 0,
              },

              { name: "Grapeseed Oil",
                lye: 0.1321,
                potash: 0.1861,
                lauric: 0,
                myristic: 0,
                palmitic: 8,
                stearic: 4,
                ricinoleic: 0,
                oleic: 20,
                linoleic: 68,
                linolenic: 0,
              },

              { name: "Hazelnut Oil",
                lye: 0.1369,
                potash: 0.1928,
                lauric: 0,
                myristic: 0,
                palmitic: 5,
                stearic: 3,
                ricinoleic: 0,
                oleic: 75,
                linoleic: 10,
                linolenic: 0,
              },

              { name: "Hempseed Oil",
                lye: 0.1359,
                potash: 0.1914,
                lauric: 0,
                myristic: 0,
                palmitic: 6,
                stearic: 2,
                ricinoleic: 0,
                oleic: 12,
                linoleic: 57,
                linolenic: 21,
              },

              { name: 'Japan Wax',
                lye: 0.153,
                potash: 0.215,
                lauric: 0,
                myristic: 1,
                palmitic: 80,
                stearic: 7,
                ricinoleic: 0,
                oleic: 4,
                linoleic: 0,
                linolenic: 0,
              },

              { name: "Jojoba Seed Oil",
                lye: 0.0695,
                potash: 0.0979,
                lauric: 0,
                myristic: 0,
                palmitic: 0,
                stearic: 0,
                ricinoleic: 0,
                oleic: 12,
                linoleic: 0,
                linolenic: 0,
              },

              { name: "Kokum Butter",
                lye: 0.135,
                potash: 0.190,
                lauric: 0,
                myristic: 0,
                palmitic: 4,
                stearic: 56,
                ricinoleic: 0,
                oleic: 36,
                linoleic: 1,
                linolenic: 0,
              },

              { name: "Kukui Nut Oil",
                lye: 0.1351,
                potash: 0.1903,
                lauric: 0,
                myristic: 0,
                palmitic: 6,
                stearic: 2,
                ricinoleic: 0,
                oleic: 20,
                linoleic: 42,
                linolenic: 29,
              },

              { name: "Lanolin",
                lye: 0.0748,
                potash: 0.1054,
                lauric: 0,
                myristic: 0,
                palmitic: 0,
                stearic: 0,
                ricinoleic: 0,
                oleic: 0,
                linoleic: 0,
                linolenic: 0,
              },

              { name: "Lard",
                lye: 0.1399,
                potash: 0.1970,
                lauric: 0,
                myristic: 1,
                palmitic: 28,
                stearic: 13,
                ricinoleic: 0,
                oleic: 46,
                linoleic: 6,
                linolenic: 0,
              },

              { name: "Linseed Oil",
                lye: 0.1358,
                potash: 0.1913,
                lauric: 0,
                myristic: 0,
                palmitic: 6,
                stearic: 3,
                ricinoleic: 0,
                oleic: 27,
                linoleic: 13,
                linolenic: 50,
              },

              { name: "Macadamia Nut Oil",
                lye: 0.1391,
                potash: 0.1959,
                lauric: 0,
                myristic: 0,
                palmitic: 9,
                stearic: 5,
                ricinoleic: 0,
                oleic: 59,
                linoleic: 2,
                linolenic: 0,
              },

              { name: "Milk Fat",
                lye: 0.1599,
                potash: 0.2252,
                lauric: 4,
                myristic: 11,
                palmitic: 28,
                stearic: 12,
                ricinoleic: 0,
                oleic: 19,
                linoleic: 2,
                linolenic: 1,
              },

              {name: "Mink Oil",
               lye: 0.1403,
               potash: 0.1976,
               lauric: 0,
               myristic: 0,
               palmitic: 0,
               stearic: 0,
               ricinoleic: 0,
               oleic: 0,
               linoleic: 0,
               linolenic: 0,
              },

              { name: "Monoi de Tahiti Oil",
                lye: 0.1796,
                potash: 0.2530,
                lauric: 44,
                myristic: 16,
                palmitic: 10,
                stearic: 3,
                ricinoleic: 0,
                oleic: 0,
                linoleic: 2,
                linolenic: 0,
              },

              { name: "Neem Tree Oil",
                lye: 0.1372,
                potash: 0.1932,
                lauric: 0,
                myristic: 2,
                palmitic: 21,
                stearic: 16,
                ricinoleic: 0,
                oleic: 46,
                linoleic: 12,
                linolenic: 0,
              },

              { name:"Olive Oil",
                lye: 0.1353,
                potash: 0.1906,
                lauric: 0,
                myristic: 0,
                palmitic: 14,
                stearic: 3,
                ricinoleic: 0,
                oleic: 69,
                linoleic: 12,
                linolenic: 1,
              },

              { name: "Ostrich Oil",
                lye: 0.1385,
                potash: 0.1951,
                lauric: 3,
                myristic: 1,
                palmitic: 26,
                stearic: 6,
                ricinoleic: 0,
                oleic: 37,
                linoleic: 17,
                linolenic: 3,
              },

              { name: "Palm Kernel Oil",
                lye: 0.1777,
                potash: 0.2503,
                lauric: 49,
                myristic: 16,
                palmitic: 8,
                stearic: 2,
                ricinoleic: 0,
                oleic: 15,
                linoleic: 3,
                linolenic: 0,
              },

              { name: "Palm Oil",
                lye: 0.1420,
                potash: 0.2000,
                lauric: 0,
                myristic: 1,
                palmitic: 44,
                stearic: 5,
                ricinoleic: 0,
                oleic: 39,
                linoleic: 10,
                linolenic: 0,
              },

              { name: "Peach Kernel Oil",
                lye: 0.1361,
                potash: 0.1917,
                lauric: 0,
                myristic: 0,
                palmitic: 6,
                stearic: 2,
                ricinoleic: 0,
                oleic: 65,
                linoleic: 25,
                linolenic: 1,
              },

              { name: "Peanut Oil",
                lye: 0.1367,
                potash: 0.1925,
                lauric: 0,
                myristic: 0,
                palmitic: 8,
                stearic: 3,
                ricinoleic: 0,
                oleic: 56,
                linoleic: 26,
                linolenic: 0,
              },

              { name: "Pine Rosin",
                lye: 0.1298,
                potash: 0.1820,
                lauric: 0,
                myristic: 0,
                palmitic: 0,
                stearic: 0,
                ricinoleic: 0,
                oleic: 0,
                linoleic: 0,
                linolenic: 0,
              },

              { name: 'Pistachio Oil',
                lye: 0.133,
                potash: 0.186,
                lauric: 0,
                myristic: 0,
                palmitic: 11,
                stearic: 1,
                ricinoleic: 0,
                oleic: 63,
                linoleic: 25,
                linolenic: 0,
              },

              { name: 'Poppy Seed Oil',
                lye: 0.138,
                potash: 0.194,
                lauric: 0,
                myristic: 0,
                palmitic: 10,
                stearic: 2,
                ricinoleic: 0,
                oleic: 17,
                linoleic: 69,
                linolenic: 2,
              },

              { name: "Pumpkin Seed Oil",
                lye: 0.1389,
                potash: 0.1956,
                lauric: 0,
                myristic: 0,
                palmitic: 11,
                stearic: 8,
                ricinoleic: 0,
                oleic: 33,
                linoleic: 50,
                linolenic: 0,
              },

              { name: "Rapeseed Oil",
                lye: 0.1328,
                potash: 0.1870,
                lauric: 0,
                myristic: 0,
                palmitic: 4,
                stearic: 1,
                ricinoleic: 0,
                oleic: 17,
                linoleic: 13,
                linolenic: 9,
              },

              { name: "Rice Bran Oil",
                lye: 0.1284,
                potash: 0.1808,
                lauric: 0,
                myristic: 1,
                palmitic: 22,
                stearic: 3,
                ricinoleic: 0,
                oleic: 38,
                linoleic: 34,
                linolenic: 2,
              },

              { name: "Safflower Oil, High Linoleic Acid",
                lye: 0.1374,
                potash: 0.1935,
                lauric: 0,
                myristic: 0,
                palmitic: 7,
                stearic:0,
                ricinoleic: 0,
                oleic: 15,
                linoleic: 75,
                linolenic: 0,
              },

              { name: "Safflower Oil, High Oleic Acid",
                lye: 0.1369,
                potash: 0.1928,
                lauric: 0,
                myristic: 0,
                palmitic: 5,
                stearic: 2,
                ricinoleic: 0,
                oleic: 77,
                linoleic: 15,
                linolenic: 0,
              },

              { name: "Sesame Seed Oil",
                lye: 0.1336,
                potash: 0.1882,
                lauric: 0,
                myristic: 0,
                palmitic: 10,
                stearic: 5,
                ricinoleic: 0,
                oleic: 40,
                linoleic: 43,
                linolenic: 0,
              },

              { name: "Shea Butter",
                lye: 0.1296,
                potash: 0.1825,
                lauric: 0,
                myristic: 0,
                palmitic: 5,
                stearic: 40,
                ricinoleic: 0,
                oleic: 48,
                linoleic: 6,
                linolenic: 0,
              },

              { name: "Soybean Oil",
                lye: 0.1359,
                potash: 0.1914,
                lauric: 0,
                myristic: 0,
                palmitic: 11,
                stearic: 5,
                ricinoleic: 0,
                oleic: 24,
                linoleic: 50,
                linolenic: 8,
              },

              { name: "Soybean Oil, 27.5% Hydrogenated",
                lye: 0.1361,
                potash: 0.1917,
                lauric: 0,
                myristic: 0,
                palmitic: 9,
                stearic: 15,
                ricinoleic: 0,
                oleic: 41,
                linoleic: 7,
                linolenic: 1,
              },

              { name: "Stearic Acid",
                lye: 0.1413,
                potash: 0.1990,
                lauric: 0,
                myristic: 0,
                palmitic: 0,
                stearic: 99,
                ricinoleic: 0,
                oleic: 0,
                linoleic: 0,
                linolenic: 0,
              },

              { name: "Sunflower Seed Oil",
                lye: 0.1358,
                potash: 0.1913,
                lauric: 0,
                myristic: 0,
                palmitic: 7,
                stearic: 4,
                ricinoleic: 0,
                oleic: 16,
                linoleic: 70,
                linolenic: 1,
              },

              { name: "Sunflower Seed Oil, High Oleic Acid",
                lye: 0.1351,
                potash: 0.1903,
                lauric: 0,
                myristic: 0,
                palmitic: 3,
                stearic: 4,
                ricinoleic: 0,
                oleic: 83,
                linoleic: 4,
                linolenic: 1,
              },

              { name: "Tallow, Beef",
                lye: 0.1419,
                potash: 0.1999,
                lauric: 2,
                myristic: 6,
                palmitic: 28,
                stearic: 22,
                ricinoleic: 0,
                oleic: 36,
                linoleic: 3,
                linolenic: 1,
              },

              { name: "Tallow, Deer",
                lye: 0.1382,
                potash: 0.1946,
                lauric: 0,
                myristic: 1,
                palmitic: 20,
                stearic: 24,
                ricinoleic: 0,
                oleic: 30,
                linoleic: 15,
                linolenic: 3,
              },

              { name: 'Tallow, Goat',
                lye: 0.138,
                potash: 0.192,
                lauric: 5,
                myristic: 11,
                palmitic: 23,
                stearic: 30,
                ricinoleic: 0,
                oleic: 29,
                linoleic: 2,
                linolenic: 0,
              },

              { name: "Tallow, Sheep",
                lye: 0.1384,
                potash: 0.1949,
                lauric: 4,
                myristic: 10,
                palmitic: 24,
                stearic: 13,
                ricinoleic: 0,
                oleic: 26,
                linoleic: 5,
                linolenic: 0,
              },

              { name: "Tamanu Seed Oil",
                lye: 0.1437,
                potash: 0.208,
                lauric: 0,
                myristic: 0,
                palmitic: 12,
                stearic: 13,
                ricinoleic: 0,
                oleic: 34,
                linoleic: 38,
                linolenic: 1,
              },

              { name: "Walnut Oil",
                lye: 0.1349,
                potash: 0.1900,
                lauric: 0,
                myristic: 0,
                palmitic: 7,
                stearic: 2,
                ricinoleic: 0,
                oleic: 18,
                linoleic: 60,
                linolenic: 0,
              },

              {name:'Watermelon Seed Oil',
               lye: 0.135,
               potash: 0.190,
               lauric: 0,
               myristic: 0,
               palmitic: 11,
               stearic: 10,
               ricinoleic: 0,
               oleic: 18,
               linoleic: 60,
               linolenic: 1,
              },

              { name: "Wheat Germ Oil",
                lye: 0.1319,
                potash: 0.1858,
                lauric: 0,
                myristic: 0,
                palmitic: 17,
                stearic: 2,
                ricinoleic: 0,
                oleic: 17,
                linoleic: 58,
                linolenic: 0,
              }
            ]

export default Saponification
